//moo is tokenizer module
const moo = require('moo')
const fs = require('mz/fs')

let lexer = moo.compile({
    WS:      /[ \t]+/,
    comment: /\/\/.*?$/,
    number:  /0|[1-9][0-9]*/,
    string:  /"(?:\\["\\]|[^\n"\\])*"/,
    true: 'true',
    false: 'false',
    lparen:  '(',
    rparen:  ')',
    dots: ':',
    semicolon: ';',
    arrow: '=>',
    returnF: 'return',
    greaterEqual: '>=',
    lessEqual: '<=',
    equal: '==',
    assign: '=',
    plus: '+',
    minus: '-',
    divide: '/',
    multiply: '*',
    modulus: '%',
    greater: '>',
    less: '<',
    and: '&',
    or: '|',
    not: '!',
    forF: 'for',
    ifF: 'if',
    then: 'then',
    elseF: 'else',
    endIf: 'end if',
    loop: 'loop',
    endLoop: 'end loop',
    whileF: 'while',
    def: 'def',
    is: 'is',
    leftCurl: '{',
    rightCurl: '}',
    print: 'print',
    record: 'record',
    endRecord: 'end record',
    comma: ',',
    dotes: '..',
    lsqPar: '[',
    rsqPar: ']',
    type: ['Int', 'Bool', 'Double', 'String'],
    new: 'new',
    identifier: /[a-zA-Z][a-zA-Z_0-9]*/,
    NL:      { match: /\n/, lineBreaks: true },
})

module.exports = lexer;


